### ISSUE TITLE
Dragonwell version number parsing failed

### ISSUE THREAD

**Issue by Accelerator1996** [actions/setup-java#642]
**Description:**
Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.

**Task version:**
Nightly task.

**Platform:**
- [x] Ubuntu
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Expected behavior:**
get correct version number.

**Actual behavior:**
get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by HarithaVattikuti** [comment]
Hello @Accelerator1996 
Thank you for creating this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by esaulpaugh** [comment]
https://github.com/esaulpaugh/headlong/actions/runs/9800088963/job/27061442613

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
> get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

Aceptado

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
- [ ] > get correct version number.
> 
> **Actual behavior:**
- [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
- [ x] > get correct version number.
> 
> **Actual behavior:**
- [x ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
- [ ] >- get correct version number.
> 
> **Actual behavior:**
- [ ] > -get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
> get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

- [ ]

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
- [ ] get correct version number.
> 
> **Actual behavior:**
- [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
> get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

- [ ]

**Comment by Chuysalgafo** [comment]
> > **Description:**
> > Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> > 
> > **Task version:**
> > Nightly task.
> > 
> > **Platform:**
> > - [x] Ubuntu
> > - [x] Windows
> > 
> > **Runner type:**
> > - [x] Hosted
> > - [x] Self-hosted
> > 
> > **Expected behavior:**
- [ ] -   get correct version number.
> > 
> > **Actual behavior:**
- [x]  > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.
> 
>

**Comment by Chuysalgafo** [comment]
> > > **Description:**
> > > Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> > > 
> > > **Task version:**
> > > Nightly task.
> > > 
> > > **Platform:**
> > > - [x] Ubuntu
> > > - [x] Windows
> > > 
> > > **Runner type:**
> > > - [x] Hosted
> > > - [x] Self-hosted
> > > 
> > > **Expected behavior:**
- [ ] > - [ ] -   get correct version number.
> > > 
> > > **Actual behavior:**
> - [x]  > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.
> > 
> > 
> 
>

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
- [ ] > get correct version number.
> 
> **Actual behavior:**
- [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
- [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

**Comment by Chuysalgafo** [comment]
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
> get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

2262f4bd9616b2cf30f6a67b8e1d49d8902ca0d2

**Comment by aparnajyothi-y** [comment]
Hello @Accelerator1996, This issue is fixed with this [PR](https://github.com/actions/setup-java/pull/643) merge hence proceeding to this issue. 
Please feel free to reach us in case of any further concerns to reopen this issue.
