### ISSUE TITLE
Tracking: V2 setup-java

### ISSUE THREAD

**Issue by konradpabjan** [actions/setup-java#98]
This issue will track the progress of the `v2` version of `setup-java`.

One of the core goals of the `v2` version is to support downloading different distributions of Java. Currently `Zulu` builds of OpenJDK are downloaded and installed but with `v2` we will be adding support for `adoptOpenJDK` builds of OpenJDK as well. Because this is a major change, a `v2` major update is warranted.

One of the main goals of `v2` is also to make `setup-java` extensible so that other distributions can be supported as well.

Major TODO items:

- [x] Create ADR that outlines and documents the roadmap and plan for the `v2` version: https://github.com/actions/setup-java/pull/97
- [x] Accept ADR after getting feedback from the community
- [x] Create `v2-preview` branch
- [x] Implement all the necessary changes and merge them into the `v2-preview` branch
- [x] Gather feedback and test using the `v2-preview` branch
- [x] After being comfortable with the `v2-preview` changes, merge the branch into `main`
- [x] Update public docs, and starter workflow to use `v2` instead of `v1` tags

**Comment by giltene** [comment]
I would suggest changing the stated goal (in the PR and ADR) to adding support for multiple distos (rather than a specific one). I believe that is the actual subject for which there is wide demand and support.

I would also propose that we add a goal to address https://github.com/actions/setup-java/issues/84 (built in use of caching) in v2, as this will likely significantly improve workflow execution times and reduce bandwidth requirements.

Another (seemingly minor, but affects expected output) item I’d propose to see addressed in v2 is https://github.com/actions/setup-java/issues/92

**Comment by maxim-lobanov** [comment]
Hello!
V2-preview is available with support of Adopt OpenJDK. We would be appreciate for any testing before `v2` stable release:
```
- name: setup-java
  uses: actions/setup-java@v2-preview
  with:
    distribution: 'adopt'
    java-version: '11'
```

**Comment by brunoborges** [comment]
@maxim-lobanov should Setup Java really continue to have the support for managing Maven's settings.xml ? Shouldn't that be done by a Maven-specific Action?

I feel this is an overeach of functionality.

**Comment by msgilligan** [comment]
The v2-preview README doesn't document that `outputs.path` and `outputs.version` are set. This would be very helpful.

**Comment by maxim-lobanov** [comment]
Thank you for pointing on it. Actually, `v2-preview` sets `path`, `version` and `distribution` properties: https://github.com/actions/setup-java/blob/v2-preview/src/distributions/base-installer.ts#L125 . I think we need to document it.

**Comment by davidkarlsen** [comment]
how is it coming along? It's now 8 months since the ADR was created..

**Comment by dmitry-shibanov** [comment]
Hello @davidkarlsen. We released `setup-java@v2-preview` two weeks ago. We're planing to release stable `setup-java@v2` next week. But If you want to try current logic for `v2` you can use `actions/setup-java@v2-preview`.
https://github.com/actions/setup-java/issues/98#issuecomment-799588722

**Comment by konradpabjan** [comment]
Docs and starter workflows have been updated! Closing out
